#!/usr/bin/env sh
#
# Copyright 2011-2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -x
set -e
git checkout -f master
git branch -D gh-pages || echo OK
git checkout --orphan gh-pages
./dev_tools/ci/code_conventions_003_documentation.sh 
temp=$(mktemp -d)
mv ./doc/build/html/* "$temp"
git rm --cached -r .
git rm -f .gitignore || echo OK
rm -fr ./*
mv "$temp"/* .
touch .nojekyll 
git add ./*
git add .nojekyll
git commit -s -m "Autogenerated documentation from master branch"
git push --force --set-upstream origin gh-pages
rm -f .gitignore .isort.cfg .travis.yml
git checkout -f master
