set -x
set -e
git checkout -f master
git branch -D gh-pages || echo OK
git checkout --orphan gh-pages
./dev_tools/ci/code_conventions_003_documentation.sh 
temp=$(mktemp -d)
mv ./doc/build/html/* "$temp"
git rm --cached -r .
git rm -f .gitignore || echo OK
rm -fr ./*
mv "$temp"/* .
touch .nojekyll 
git add ./*
git add .nojekyll
git commit -s -m "Autogenerated documentation from master branch"
git push --force --set-upstream origin gh-pages
rm -f .gitignore .isort.cfg .travis.yml
git checkout -f master
